-- inset categorias
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Aceites para masaje');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Básicos');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Bio Jelly Spa');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Bombas Efervescentes');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Complementos');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Exfoliantes');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Herramientas');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Hidratación');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Kit');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Lociones');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Mascarillas');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Sales Efervescentes');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Sales Minerales');
INSERT INTO `diag_e-r_bgspa`.`categorias` (`nombre`) VALUES ('Sanitizantes y Limpiadores');

-- dirección
INSERT INTO `diag_e-r_bgspa`.`direccion` (`colonia`, `calle`, `numero`, `codigo_postal`, `estado`, `ciudad`) VALUES ('San Fernando', 'Morelos', '12', '13400', 'Ciudad de México', 'Ciudad de México');
INSERT INTO `diag_e-r_bgspa`.`direccion` (`colonia`, `calle`, `numero`, `codigo_postal`, `estado`, `ciudad`) VALUES ('La condesa', 'Yuatepec', '15', '06140', 'Ciudad de México', 'Ciudad de México');
INSERT INTO `diag_e-r_bgspa`.`direccion` (`colonia`, `calle`, `numero`, `codigo_postal`, `estado`, `ciudad`) VALUES ('Centro', 'Fco. I. Madero', '88', '94300', 'Veracruz', 'Orizaba');
INSERT INTO `diag_e-r_bgspa`.`direccion` (`colonia`, `calle`, `numero`, `codigo_postal`, `estado`, `ciudad`) VALUES ('Sierra de Alica', 'Jesús González', '304', '98050', 'Zacatecaz', 'Zacatecaz');
INSERT INTO `diag_e-r_bgspa`.`direccion` (`colonia`, `calle`, `numero`, `codigo_postal`, `estado`, `ciudad`) VALUES ('Selene', 'Mar de las lluvias', '34', '13440', 'Cuidad de México', 'Ciudad de México');

-- usuario

INSERT INTO `diag_e-r_bgspa`.`usuarios` (`nombre`, `apellido`, `telefono`, `email`, `contrasena`, `direccion_iddireccion`) VALUES ('Carlos', 'Mendoza', '5678904567', 'carlos_8@outllook.com', 'Carli.89', '1');
INSERT INTO `diag_e-r_bgspa`.`usuarios` (`nombre`, `apellido`, `telefono`, `email`, `contrasena`, `direccion_iddireccion`) VALUES ('Diana', 'Sandoval', '5556789034', 'dian_s@gmail.com', 'Dias.234', '2');
INSERT INTO `diag_e-r_bgspa`.`usuarios` (`nombre`, `apellido`, `telefono`, `email`, `contrasena`, `direccion_iddireccion`) VALUES ('Pamela', 'Montoya', '6789546755', 'pam_7888@gmail.com', 'pamE.879', '3');
INSERT INTO `diag_e-r_bgspa`.`usuarios` (`nombre`, `apellido`, `telefono`, `email`, `contrasena`, `direccion_iddireccion`) VALUES ('Daniel', 'Rosas', '5567890065', 'danrosas@outlook.com', 'dani_R90', '4');
INSERT INTO `diag_e-r_bgspa`.`usuarios` (`nombre`, `apellido`, `telefono`, `email`, `contrasena`, `direccion_iddireccion`) VALUES ('Diego', 'Rivera', '5540987632', 'diegoR@gmail.com', 'dieGo87.', '5');

-- productos


INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Aceite para masaje aroma toronja 250 ml', 'ACT', 'La toronja posee magnificas propiedades cosméticas para la piel, actúa como astringente y reafirmante. Ayuda a reafirmar el tejido. No mancha la ropa, ideal para masaje, brinda tranquilidad, descanso, alivio y relajación al cuerpo.', '147', '/img/Productos/aceitesParaMasaje/aceite_para_masaje_TORONJA_250_ml.png', '1');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Aceite para masaje aroma toronja 1 litro', 'ACT1L', 'La toronja posee magnificas propiedades cosméticas para la piel, actúa como astringente y reafirmante. Ayuda a reafirmar el tejido. No mancha la ropa, ideal para masaje, brinda tranquilidad, descanso, alivio y relajación al cuerpo.', '347', '/img/Productos/aceitesParaMasaje/aceite_para_masaje_TORONJA_1_Litro.png', '1');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Aceite para masaje aroma almendras dulces 250 ml', 'ACA', 'Suaviza y proporciona elasticidad a la piel, evita la resequedad de la misma. Tiene efectos emolientes, suaviza y protege la piel.', '147', '/img/Productos/aceitesParaMasaje/aceite_para_masaje_ALMENDRAS_DULCES_250_ml.png', '1');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Aceite para masaje aroma almendras dulces 1 litro', 'ACA1L', 'Suaviza y proporciona elasticidad a la piel, evita la resequedad de la misma. Tiene efectos emolientes, suaviza y protege la piel.', '347', '/img/Productos/aceitesParaMasaje/aceite_para_masaje_ALMENDRAS_DULCES_1_Litro.png', '1');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Lija pie de madera para pedicure', 'LPIE', 'De alta calidad, ergonómica, para todo tipo de piel; elimina callos y piel muerta, dejando tus pies suaves y tersos.', '18', '/img/Productos/Basicos/lija_Pie_Pedicure_De_Madera_.png', '2');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Ablandador de callosidades 60ml', 'AC60', 'Líquido ideal para eliminar callosidades y células muertas, promueve la regeneración celular revelando la mejor versión de la piel.', '57', '/img/Productos/Basicos/ablandador_de_callosidades_60_ml.png', '2');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Ablandador de callosidades 1 litro', 'AC1L', 'Líquido ideal para eliminar callosidades y células muertas, promueve la regeneración celular revelando la mejor versión de la piel.', '490', '/img/Productos/Basicos/ablandador_de_callosidades_1_litro.png', '2');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Ablandador de callosidades galón 3,785 l', 'ACGL', 'Líquido ideal para eliminar callosidades y células muertas, promueve la regeneración celular revelando la mejor versión de la piel.', '997', '/img/Productos/Basicos/ablandador_de_callosidades_Galon_3,785_l.png', '2');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Removedor de cutículas 60ml', 'RC60', 'Ayuda a reblandecer la piel muerta o dañada de las cutículas antes de retirarlas. Humecta el contorno de las uñas, deja la piel suave, además de contener emolientes y humectantes desprende fácilmente la cutícula del contorno de las uñas sin lastimarlas.', '37', '/img/Productos/Basicos/BG_SPA_BASICOS_REMOVEDOR_DE_CUTICULA.png', '2');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Removedor de cutículas 1 litro', 'RC1L', 'Ayuda a reblandecer la piel muerta o dañada de las cutículas antes de retirarlas. Humecta el contorno de las uñas, deja la piel suave, además de contener emolientes y humectantes desprende fácilmente la cutícula del contorno de las uñas sin lastimarlas.', '445', '/img/Productos/Basicos/removedor_de_cuticulas_1_litro.png', '2');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Removedor de cutículas galón 3,785 l', 'RCGL', 'Ayuda a reblandecer la piel muerta o dañada de las cutículas antes de retirarlas. Humecta el contorno de las uñas, deja la piel suave, además de contener emolientes y humectantes desprende fácilmente la cutícula del contorno de las uñas sin lastimarlas.', '945', '/img/Productos/Basicos/removedor_de_cuticulas _Galon_3,785_l.png', '2');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 90g. Tropical', 'JTR', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '79', '/img/Productos/bioJellySpa/BIO JELLY SPA 90g. TROPICAL .png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 90g. Té Verde', 'JTE', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '79', '/img/Productos/bioJellySpa/BIO JELLY SPA 90g. TÉ VERDE.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 90g. Coconut', 'JC', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '79', '/img/Productos/bioJellySpa/BIO JELLY SPA 90g. COCONUT.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 90g. Flowers', 'JF', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '79', '/img/Productos/bioJellySpa/BIO JELLY SPA 90g. FLOWERS.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 90g. Menta', 'JM', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '79', '/img/Productos/bioJellySpa/BIO JELLY SPA 90g. MENTA.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 90g. Limón', 'JLI', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '79', '/img/Productos/bioJellySpa/BIO JELLY SPA 90g. LIMÓN.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 90g. Naranja', 'JN', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '79', '/img/Productos/bioJellySpa/BIO JELLY SPA 90g. NARANJA.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 90g. Lavanda', 'JLA', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '79', '/img/Productos/bioJellySpa/BIO JELLY SPA 90g. LAVANDA.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 500g. Tropical', 'JMTR', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '245', '/img/Productos/bioJellySpa/BIO JELLY SPA 500g. TROPICAL.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 500g. Té Verde', 'JMTE', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '245', '/img/Productos/bioJellySpa/BIO JELLY SPA 90g. TÉ VERDE.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 500g. Coconut', 'JMC', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '245', '/img/Productos/bioJellySpa/BIO JELLY SPA 500g. COCONUT.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 500g. Flowers', 'JMF', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '245', '/img/Productos/bioJellySpa/BIO JELLY SPA 500g. FLOWERS.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 500g. Menta', 'JMM', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '245', '/img/Productos/bioJellySpa/BIO JELLY SPA 500g. MENTA.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 500g. Limón', 'JMLI', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '245', '/img/Productos/bioJellySpa/BIO JELLY SPA 500g. LIMÓN.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 500g. Naranja', 'JMN', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '245', '/img/Productos/bioJellySpa/BIO JELLY SPA 500g. NARANJA.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 500g. Lavanda', 'JMLA', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '245', '/img/Productos/bioJellySpa/BIO JELLY SPA 500g. LAVANDA.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 1 Kg. Tropical', 'JKTR', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '450', '/img/Productos/bioJellySpa/BIO JELLY SPA 1 kg. TROPICAL.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 1 Kg. Té Verde', 'JKTE', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '450', '/img/Productos/bioJellySpa/BIO JELLY SPA 1 kg. TÉ VERDE.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 1 Kg. Coconut', 'JKC', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '450', '/img/Productos/bioJellySpa/BIO JELLY SPA 1 kg. COCONUT.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 1 Kg. Flowers', 'JKF', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '450', '/img/Productos/bioJellySpa/BIO JELLY SPA 1 kg. FLOWERS.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 1 Kg. Menta', 'JKM', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '450', '/img/Productos/bioJellySpa/BIO JELLY SPA 1 kg. MENTA.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 1 Kg. Limón', 'JKLI', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '450', '/img/Productos/bioJellySpa/BIO JELLY SPA 1 kg. LIMÓN.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 1 Kg. Naranja', 'JKN', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '450', '/img/Productos/bioJellySpa/BIO JELLY SPA 1 kg. NARANJA.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bio Jelly Spa 1 Kg. Lavanda', 'JKLA', 'Producto libre de químicos o conservantes dañinos para la piel y es totalmente biodegradable. En sus beneficios destaca una hidratación profunda para la piel, activa la circulación sanguínea, desinflama tus pies, relaja músculos, suaviza la piel, exfolia ligeramente y elimina toxinas que se encuentran en nuestro cuerpo.', '450', '/img/Productos/bioJellySpa/BIO JELLY SPA 1 kg. LAVANDA.png', '3');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Docena Bath bombs Colección RAINBOW BOMBS (Bomba de baño efervescente)', '12BER', 'Al sumergirlas generan un efecto relajante, terapéutico y lleno de nutrientes para la piel. Además, son libres de parabenos, aceites minerales, sulfatos, colorantes artificiales o cualquier derivado del petróleo. Después según el aroma y aceites esenciales que posean, tendrán unas propiedades específicas.', '197', '/img/Productos/bombasEfervescentes/BOMBAS_EFERVESCENTES_RAINBOW.png', '4');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Docena Bath bombs Colección GEMNSTONE (Bomba de baño efervescente)', '12BEG', 'Al sumergirlas generan un efecto relajante, terapéutico y lleno de nutrientes para la piel. Además, son libres de parabenos, aceites minerales, sulfatos, colorantes artificiales o cualquier derivado del petróleo. Después según el aroma y aceites esenciales que posean, tendrán unas propiedades específicas.', '197', '/img/Productos/bombasEfervescentes/BOMBAS_EFERVESCENTES_GEMSTONE.png', '4');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Docena Bath bombs Colección HEALING (Bomba de baño efervescente)', '12BEH', 'Al sumergirlas generan un efecto relajante, terapéutico y lleno de nutrientes para la piel. Además, son libres de parabenos, aceites minerales, sulfatos, colorantes artificiales o cualquier derivado del petróleo. Después según el aroma y aceites esenciales que posean, tendrán unas propiedades específicas.', '197', '/img/Productos/bombasEfervescentes/BOMBAS_EFERVESCENTES_HEALING.png', '4');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Bath bomb individual (Bomba de baño efervescente)', 'BE', 'Al sumergirlas generan un efecto relajante, terapéutico y lleno de nutrientes para la piel. Además, son libres de parabenos, aceites minerales, sulfatos, colorantes artificiales o cualquier derivado del petróleo. Después según el aroma y aceites esenciales que posean, tendrán unas propiedades específicas.', '18', '/img/Productos/bombasEfervescentes/BATH BOMB INDIVIDUAL (Bomba de baño efervescente).png', '4');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Serum ácido hialurónico + vitamina c 60ml', 'SEAH', 'Detiene el avance de la onicomicosis, contiene vitamina E, calcio y proteína natural, su fórmula está diluida con extracto de glicerina para una consistencia flexible, promueve el crecimiento de las uñas y aumenta su resistencia, ayudando a evitar su rotura, favorece la remineralización y reestructuración de las uñas; gracias al aumento de la cantidad y calidad de silicio y keratina, devuelve el aspecto natural a las uñas y cutículas.', '129', '/img/Productos/complementos/Sèrum Ácido Hialurónico + Vitamina C 60ml.png', '5');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Removedor de gel y acrílico 15ml', 'RGA', 'Simplemente quite el brillo, aplique suavemente, espere de 2 a 5 minutos, se verá el progreso en la superficie de la uña, luego retire suavemente la uña con un pequeño empujador de acero. Sin tedioso proceso de eliminación, sin largos tiempos de espera, ahorre tiempo.', '45', '/img/Productos/complementos/Removedor de Gel y acrilico 15ml.png', '5');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Aceite de cutícula 15ml', 'AC', 'Hidratante especial para cutícula, con esencias aromáticas. Ideal para hidratar, nutrir y lubricar la piel del área de la cutícula.', '21', '/img/Productos/complementos/Aceite de cuticula 15ml.png', '5');

INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Pegamento para foil 15ml', 'PF', 'Aplicar y expandir con la brocha, el producto es de color blanco y solo hay que esperar de 60 a 90 segundos, para que este seque y al hacerlo el producto está listo, ¿Cómo sabemos que ya está listo? Es sencillo hasta que el pegamento de color blanco al aplicar se vuelva transparente.', '25', '/img/Productos/complementos/Pegamento para foil  15ml.png', '5');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Latex líquido (cubre cutícula) 15ml', 'LXL', 'Fácil de quitar y respetuoso con el medio ambiente. Aplique a las áreas que desee sin esmalte cuando esté pintando sus uñas.', '25', '/img/Productos/complementos/Latex líquido (cubre cuticula) 15ml.png', '5');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Berry Scrub exfoliante profundo de frutos rojos 300 g', 'EXFR', 'Exfoliante profundo con ingredientes naturales. Beneficios desintoxicantes, vitamina C, antioxidantes y vitamina E. Con partículas exfoliantes que ayuda a eliminar la piel dañada, las células muertas y las imperfecciones revelando el mejor estado de la piel, sus aceites ayudan a blanquear la piel.', '165', '/img/Productos/Exfoliante/EXFOLIANTE_FRUTOS_ROJOS.png', '6');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Honey Scrub exfoliante oleoso de miel-avena 300 g', 'EXMI', 'Ayudan a retirar células muertas dejando una piel más clara y aportando una apariencia más tersa y suave. La avena elimina la piel muerta y deja una piel radiante. Es un gran exfoliante para el cuerpo que sólo contiene ingredientes naturales, dejando la piel más fresca. Ingredientes de exfoliación suave, elimina la suciedad de la piel y tiene el doble efecto de hidratar y suavizar la piel.', '165', '/img/Productos/Exfoliante/EXFOLIANTE_MIEL_AVENA.png', '6');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Tina para pedicure plegable', 'TP', 'Diseño plegable, ahorro de espacio y fácil de llevar al exterior. Lo suficientemente grueso, no es fácil de deformar. Con 4 rodillos de masaje', '237', '/img/Productos/herramientas/Tina para Pedicure Plegable.webp', '7');

INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Tina para pedicure sencilla c/ rodillos', 'TINA', 'Con un diseño moderno y forma anatómica, tiene un amplio espacio para acomodar los pies. Hecha de material altamente resistente a los productos químicos, facilita la limpieza y proporciona durabilidad, lo que permite trabajar con agua caliente o fría.', '110', '/img/Productos/herramientas/Tina para pedicure Sencilla c rodillos.png', '7');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Razor Dead Skin cuchilla removedora de piel muerta', 'RDS', 'La curva se adapta a cualquier tipo de pie siendo seguro y sin preocupaciones para el usuario. Es una técnica 100% segura ya que no es bisturí. Esta técnica también es conocida como técnica de raspado.', '79', '/img/Productos/herramientas/Razor Dead Skin cuchilla removedora de piel muerta.jpg', '7');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Crema hidratante 250ml aroma coco', 'CRCO', 'Su fórmula permite una rápida absorción, contiene Complejo Vitamina E que ayuda a que la piel luzca joven y radiante. Además de dejarla hidratada, suave y con un delicioso aroma que te acompañara durante el día.', '97', '/img/Productos/hidratacion/CREMA_HIDRATANTE250ML_COCO.png', '8');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Crema hidratante 250ml aroma cherry', 'CRC', 'Su fórmula permite una rápida absorción, contiene Complejo Vitamina E que ayuda a que la piel luzca joven y radiante. Además de dejarla hidratada, suave y con un delicioso aroma que te acompañara durante el día.', '97', '/img/Productos/hidratacion/CREMA_HIDRATANTE250ML_CHERRY.png', '8');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Crema hidratante 250ml aroma pera', 'CRP', 'Su fórmula permite una rápida absorción, contiene Complejo Vitamina E que ayuda a que la piel luzca joven y radiante. Además de dejarla hidratada, suave y con un delicioso aroma que te acompañara durante el día.', '97', '/img/Productos/hidratacion/CREMA_HIDRATANTE250ML_PERA.png', '8');

INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Crema hidratante 250ml aroma mango', 'CRM', 'Su fórmula permite una rápida absorción, contiene Complejo Vitamina E que ayuda a que la piel luzca joven y radiante. Además de dejarla hidratada, suave y con un delicioso aroma que te acompañara durante el día.', '97', '/img/Productos/hidratacion/CREMA_HIDRATANTE250ML_MANGO.png', '8');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Crema hidratante 250ml aroma freesia', 'CRF', 'Su fórmula permite una rápida absorción, contiene Complejo Vitamina E que ayuda a que la piel luzca joven y radiante. Además de dejarla hidratada, suave y con un delicioso aroma que te acompañara durante el día.', '7', '/img/Productos/hidratacion/CREMA_HIDRATANTE250ML_FREESIA.png', '8');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Spray hidratante bifásico aroma Cherry 250 ml.', 'SHCH', 'Hidrata y brinda suavidad a la piel, humecta y es de rápida absorción, brinda una sensación ligera y suave con un delicioso aroma.', '87', '/img/Productos/hidratacion/Spray_Hidratante_BifasicoCHERRY250ml.png', '8');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Spray hidratante bifásico aroma Coco 250 ml.', 'SHCO', 'Hidrata y brinda suavidad a la piel, humecta y es de rápida absorción, brinda una sensación ligera y suave con un delicioso aroma.', '87', '/img/Productos/hidratacion/Spray_Hidratante_Bifasico_COCO250ml.png', '8');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Kit para pedicure (10 pzas + bolsa))', 'BGKIT', 'Este set cuenta con todo lo necesario para que puedas dar un masaje de pies y prepararlos para la pedicura. El kit incluye: 1 sal mineral de 350g, 1 sal efervescente 300g, 1 exfoliante 300 g, 1 mascarilla aclaradora o refrescante, 1 lija pie, 1 bomba efervescente, 1 bio jelly spa de 90g (incluye diluyente), 1 crema hidratante, 1 ablandador de callos 60ml, 1 removedor de cutículas 60ml, además de la bolsa cute.', '830', '/img/Productos/kitsSpa/KIT_PEDICURE(10Pz_Bolsa).png', '9');

INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Loción refrescante para pies 250 ml', 'LRP', 'La crema refrescante para pies es un tratamiento auxiliar para piernas y pies cansados. Brinda una sensación de frescura y relajación, suaviza e hidrata la piel. Excelente auxiliar desinflamatorio que activa la circulación en combinación con el masaje. Contiene alcanfor y mentol, desinflamatorio, refrescante, aromatizante y agente antimicrobiano.', '77', '/img/Productos/locionRefrescante/LOCION_REFRESCANTE_PIES.png', '10');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Loción refrescante para pies 1 litro', '231', 'La crema refrescante para pies es un tratamiento auxiliar para piernas y pies cansados. Brinda una sensación de frescura y relajación, suaviza e hidrata la piel. Excelente auxiliar desinflamatorio que activa la circulación en combinación con el masaje. Contiene alcanfor y mentol, desinflamatorio, refrescante, aromatizante y agente antimicrobiano.', '231', '/img/Productos/locionRefrescante/Locion Refrescante para Pies 1 Litro  .png', '10');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Fade Mask (aclarante) té verde y sándalo 300 g', 'MTV', 'Mascarilla nutritiva a base de arcilla blanca, contiene sándalo que es un antienvejecimiento, nos ayuda a reducir marcas de la piel como las cicatrices y té verde que rejuvenece las células de la piel, ayuda a desinflamar la piel. Limpiando a profundidad regenerando las células de la superficie y estimulando la renovación de estas.', '165', '/img/Productos/Mascarillas/MASCARILLA_TE_VERDE_SANDALO.png', '11');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Fresh Mask (refrescante) mentol y hierbabuena 300g', 'MMH', 'Elimina las células muertas, las impurezas y el exceso de grasa. Es refrescante y deja la piel limpia, la revitaliza, suaviza, hidrata y nutre. Regula el exceso de grasa en la piel.La mascarilla Mentol-Hierbabuena ayuda a eliminar células muertas e impurezas y a regular el exceso de grasa cutánea, dejando la piel profundamente limpia, revitalizada, suave e hidratada.', '165', '/img/Productos/Mascarillas/MASCARILLA_MENTOL_HIERBABUENA.png', '11');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Sales efervescentes aroma Menta 300 g.', 'SEM', 'Especialmente indicadas para pies y manos secas, pies agrietados, reduce las cutículas ásperas, el mal olor de pies, sudor, infecciones, picazón en los pies y alivia el cansancio en los pies. Sales minerales efervescentes ideales para manicure y pedicure, estas están hechas a base de ingredientes naturales. Nos ayuda a blanquear la piel y eliminar ligeras manchas e imperfecciones.', '79', '/img/Productos/salesEfervescente/SALES_EFERVESCENTES_MENTA.png', '12');

INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Sales efervescentes aroma piña & coco 300 g.', 'SEP', 'Especialmente indicadas para pies y manos secas, pies agrietados, reduce las cutículas ásperas, el mal olor de pies, sudor, infecciones, picazón en los pies y alivia el cansancio en los pies. Sales minerales efervescentes ideales para manicure y pedicure, estas están hechas a base de ingredientes naturales. Nos ayuda a blanquear la piel y eliminar ligeras manchas e imperfecciones.', '79', '/img/Productos/salesEfervescente/SALES_EFERVESCENTES_PIÑACOCO.png', '12');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Sales efervescentes aroma Mix&Match (Tutti Frutti) 300 g', 'SETF', 'Especialmente indicadas para pies y manos secas, pies agrietados, reduce las cutículas ásperas, el mal olor de pies, sudor, infecciones, picazón en los pies y alivia el cansancio en los pies. Sales minerales efervescentes ideales para manicure y pedicure, estas están hechas a base de ingredientes naturales. Nos ayuda a blanquear la piel y eliminar ligeras manchas e imperfecciones.', '79', '/img/Productos/salesEfervescente/SALES_EFERVESCENTES_MIX_MATCH.png', '12');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma canela 350 g.', 'MTCA', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '59', '/img/Productos/salesMinerales/SALES_MINERALES350g_CANELA.png', '13');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma menta 350 g.', 'MTM', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '59', '/img/Productos/salesMinerales/SALES_MINERALES350g_MENTA.png', '13');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma lavanda 350 g.', 'MTL', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '59', '/img/Productos/salesMinerales/SALES_MINERALES350g_LAVANDA.png', '13');

INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma citricos  350 g.', 'MTCI', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '59', '/img/Productos/salesMinerales/SALES_MINERALES350g_CITRICOS.png', '13');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma piña-coco 350 g.', 'MTP', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '59', '/img/Productos/salesMinerales/SALES_MINERALES350g_PIÑACOCO.png', '13');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma canela 500g.', 'MTMCA', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '95', '/img/Productos/salesMinerales/SALES_MINERALES350g_CANELA.png', '13');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma menta 500g.', 'MTMM', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '95', '/img/Productos/salesMinerales/SALES_MINERALES500G_MENTA.png', '13');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma lavanda 500g.', 'MTML', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '95', '/img/Productos/salesMinerales/SALES_MINERALES500G_LAVANDA.png', '13');

INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma citricos 500g.', 'MTMCI', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '95', '/img/Productos/salesMinerales/SALES_MINERALES500G_CITRICOS.png', '13');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma piña-coco 500g.', 'MTMP', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '95', '/img/Productos/salesMinerales/SALES_MINERALES500G_PIÑACOCO.png', '13');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma canela 1 kg.', 'MT1CA', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '169', '/img/Productos/salesMinerales/SALES_MINERALES1KG_CANELA.png', '13');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma menta 1 kg.', 'MT1M', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '169', '/img/Productos/salesMinerales/SALES_MINERALES1KG_MENTA.png', '13');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma lavanda 1 kg.', 'MT1L', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '169', '/img/Productos/salesMinerales/SALES_MINERALES1KG_LAVANDA.png', '13');

INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma citricos  1 kg.', 'MT1C1', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '169', '/img/Productos/salesMinerales/SALES_MINERALES1KG_CITRICOS.png', '13');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Mineral Tuzlar Sales minerales aroma piña-coco 1 kg.', 'MT1P', 'Las sales minerales BG SPA contiene elementos químicos naturales. Estos elementos de forma natural tienen beneficiosos efectos sobre nuestro cuerpo, entre otros son cicatrizantes y ayudan a eliminar toxinas, combaten el reuma y suavizan la piel. Los baños con sales minerales son relajantes. Alivian los dolores musculares y desintoxican la piel. También contiene aceites esenciales y extractos naturales para exfoliar suavemente, hidratar y dejar la piel con una sensación sedosa y suave.', '169', '/img/Productos/salesMinerales/SALES_MINERALES_1KG_PIÑACOCO.png', '13');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Sanitizer bombs (para desinfectar la tina de pedicure) 500 g (aprox. 40pz)', 'BES', 'Tabletas desinfectantes para tina de pedicura, ayudan a prevenir hongo, pie de atleta, etc.', '219', '/img/Productos/sanitizanteYLimpiadores/Sanitizer Bombs (para desinfectar la tina de pedicure) 500 g (aprox 40pz).png', '14');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Shampoo espumante antibacterial aroma arándano 250 ml', 'SEAA', 'El shampoo espumante antibacterial es un producto muy efectivo con un agradable aroma dejando el área completamente limpia, suave y humectada con su protección antibacterial elimina efectivamente las bacterias causantes de múltiples enfermedades. Este shampoo es biodegradable.', '59', '/img/Productos/sanitizanteYLimpiadores/Shampoo_Espumante_Antibacterial_ARANDANO250ml.png', '14');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Shampoo espumante antibacterial aroma arándano 1 litro', 'SEA1L', 'El shampoo espumante antibacterial es un producto muy efectivo con un agradable aroma dejando el área completamente limpia, suaves y humectada y con su protección antibacterial elimina efectivamente las bacterias causantes de múltiples enfermedades. Este shampoo es biodegradable.', '187', '/img/Productos/sanitizanteYLimpiadores/Shampoo Espumante Antibacterial ARANDANO 1 Litro  .png', '14');

INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Sani spray antiséptico 250 ml', 'SSA', 'Solución antiséptica recomendada para la desinfección de espacios y superficies, además no produce la oxidación de herramientas por lo que también se usa para desinfectar este material.', '67', '/img/Productos/sanitizanteYLimpiadores/SANI_SPRAY_ANTISEPTICO250ml.png', '14');
INSERT INTO `diag_e-r_bgspa`.`productos` (`nombre`, `sku`, `descripcion`, `precio`, `img`, `categorias_idcategorias`) VALUES ('Sani spray antiséptico 1 litro', 'SA1L', 'Solución antiséptica recomendada para la desinfección de espacios y superficies, además no produce la oxidación de herramientas por lo que también se usa para desinfectar este material.', '220', '/img/Productos/sanitizanteYLimpiadores/Sani Spray Antiseptico 1 litro  .png', '14');

-- pedidos
INSERT INTO `diag_e-r_bgspa`.`pedidos` (`cantidad`, `costototal`, `usuarios_idusuarios`, `usuarios_direccion_iddireccion`) VALUES ('10', '1790', '1', '1');
INSERT INTO `diag_e-r_bgspa`.`pedidos` (`cantidad`, `costototal`, `usuarios_idusuarios`, `usuarios_direccion_iddireccion`) VALUES ('3', '1350', '2', '2');
INSERT INTO `diag_e-r_bgspa`.`pedidos` (`cantidad`, `costototal`, `usuarios_idusuarios`, `usuarios_direccion_iddireccion`) VALUES ('4', '980', '3', '3');
INSERT INTO `diag_e-r_bgspa`.`pedidos` (`cantidad`, `costototal`, `usuarios_idusuarios`, `usuarios_direccion_iddireccion`) VALUES ('18', '324', '4', '4');
INSERT INTO `diag_e-r_bgspa`.`pedidos` (`cantidad`, `costototal`, `usuarios_idusuarios`, `usuarios_direccion_iddireccion`) VALUES ('6', '474', '5', '5');

-- prod has pedido
INSERT INTO `diag_e-r_bgspa`.`productos_has_pedidos` (`productos_idprodcutos`, `productos_categorias_idcategorias`, `pedidos_idpedidos`, `pedidos_usuarios_idusuarios`, `pedidos_usuarios_direccion_iddireccion`) VALUES ('1', '1', '1', '1', '1');
INSERT INTO `diag_e-r_bgspa`.`productos_has_pedidos` (`productos_idprodcutos`, `productos_categorias_idcategorias`, `pedidos_idpedidos`, `pedidos_usuarios_idusuarios`, `pedidos_usuarios_direccion_iddireccion`) VALUES ('2', '2', '2', '2', '2');
INSERT INTO `diag_e-r_bgspa`.`productos_has_pedidos` (`productos_idprodcutos`, `productos_categorias_idcategorias`, `pedidos_idpedidos`, `pedidos_usuarios_idusuarios`, `pedidos_usuarios_direccion_iddireccion`) VALUES ('3', '3', '3', '3', '3');
INSERT INTO `diag_e-r_bgspa`.`productos_has_pedidos` (`productos_idprodcutos`, `productos_categorias_idcategorias`, `pedidos_idpedidos`, `pedidos_usuarios_idusuarios`, `pedidos_usuarios_direccion_iddireccion`) VALUES ('4', '4', '4', '4', '4');
INSERT INTO `diag_e-r_bgspa`.`productos_has_pedidos` (`productos_idprodcutos`, `productos_categorias_idcategorias`, `pedidos_idpedidos`, `pedidos_usuarios_idusuarios`, `pedidos_usuarios_direccion_iddireccion`) VALUES ('5', '5', '5', '5', '5');


